name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Rust project
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - hold-my-cosmo-contract
          - hold-my-cosmo-ios-app
          - hold-my-cosmo-website

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build and Test
      working-directory: ${{ matrix.project }}
      run: |
        cd ${{ matrix.project }}
        cargo build --verbose
        cargo test --verbose

    - name: Run rust-tarpaulin
      uses: actions-rs/tarpaulin@v0.1.0
      working-directory: ${{ matrix.project }}

    # - name: Publish Coverage Report to Codecov
    #   uses: codecov/codecov-action@v1.0.2
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}

    # - name: Archive code coverage results
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: code-coverage-report
    #     path: ${{ matrix.project }}/cobertura.xml


# name: Rust

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# env:
#   CARGO_TERM_COLOR: always

# jobs:
#   build:
#     name: Rust project
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         project:
#           - hold-my-cosmo-contract
#           - hold-my-cosmo-ios-app
#           - hold-my-cosmo-website

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v3

#     - name: Install stable toolchain
#       uses: actions-rs/toolchain@v1
#       with:
#         toolchain: stable
#         override: true

#     - name: Build and Test
#       run: |
#         cd ${{ matrix.project }}
#         cargo build --verbose
#         cargo test --verbose

#     - name: Run cargo-tarpaulin
#       run: |
#         cd ${{ matrix.project }}
#         cargo install cargo-tarpaulin --force
#         cargo tarpaulin --out Xml

#     - name: Publish Coverage Report to Codecov
#       uses: codecov/codecov-action@v1.0.2
#       with:
#         token: ${{ secrets.CODECOV_TOKEN }}

#     - name: Archive code coverage results
#       uses: actions/upload-artifact@v2
#       with:
#         name: code-coverage-report
#         path: ${{ matrix.project }}/cobertura.xml


# name: Rust

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# env:
#   CARGO_TERM_COLOR: always

# jobs:
#   build:
#     name: Rust project
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         project:
#           - hold-my-cosmo-contract
#           - hold-my-cosmo-ios-app
#           - hold-my-cosmo-website

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v3

#     - name: Install stable toolchain
#       uses: actions-rs/toolchain@v1
#       with:
#         toolchain: stable
#         override: true

    # - name: rust-tarpaulin
    #   uses: actions-rs/tarpaulin@v0.1.0


#     # - name: Run cargo-tarpaulin 0.15.0 1-trhreads
#     #   uses: actions-rs/tarpaulin@v0.1
#     #   with:
#     #     version: '0.15.0'
#     #     args: '-- --test-threads 1'

#     - name: Publish Coverage Report to Codecov
#       uses: codecov/codecov-action@v1.0.2
#       with:
#         token: ${{ secrets.CODECOV_TOKEN }}

#     - name: Archive code coverage results
#       uses: actions/upload-artifact@v2
#       with:
#         name: code-coverage-report
#         path: cobertura.xml
