name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        project:
          - hold-my-cosmo-contract
          - hold-my-cosmo-ios-app
          - hold-my-cosmo-website

    steps:
    - uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: stable

    - name: Build and Test
      run: |
        cd ${{ matrix.project }}
        cargo build --verbose
        cargo test --verbose
